package org.schabi.newpipe.extractor.services.youtube.extractors.kiosk;

import org.schabi.newpipe.extractor.StreamingService;
import org.schabi.newpipe.extractor.downloader.Downloader;
import org.schabi.newpipe.extractor.exceptions.ContentNotSupportedException;
import org.schabi.newpipe.extractor.exceptions.ExtractionException;
import org.schabi.newpipe.extractor.exceptions.ParsingException;
import org.schabi.newpipe.extractor.linkhandler.ListLinkHandler;

import javax.annotation.Nonnull;
import java.io.IOException;

public class YoutubeTrendingMusicExtractor extends YoutubeChartsBaseKioskExtractor {

    public YoutubeTrendingMusicExtractor(final StreamingService streamingService,
                                         final ListLinkHandler linkHandler,
                                         final String kioskId) {
        super(streamingService, linkHandler, kioskId, "TRENDING_VIDEOS");
    }

    @Override
    public void onFetchPage(@Nonnull final Downloader downloader)
            throws IOException, ExtractionException {
        if (!YT_CHARTS_SUPPORTED_COUNTRY_CODES.contains(
                getExtractorContentCountry().getCountryCode())) {
            throw new ContentNotSupportedException(
                    "YouTube Charts doesn't support this country for trending music videos charts");
        }
        super.onFetchPage(downloader);
    }

    @Nonnull
    @Override
    public String getName() throws ParsingException {
        // This is the official YouTube Charts name, even if autogenerated tracks and unofficial
        // contents are returned
        return "Trending Music Videos";
    }
}
