language: java

script:
  - ./gradlew check
  - ./gradlew javadoc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build/docs
  on:
    branch: master
