package org.schabi.newpipe.extractor.services.niconico.extractors;

import com.grack.nanojson.JsonObject;
import com.grack.nanojson.JsonWriter;

public class NiconicoDMCPayloadBuilder {
    public static String BuildJSON(JsonObject obj)
    {
        return JsonWriter.string()
                .object()
                    .object("session")
                        .value("recipe_id", obj.getString("recipeId"))
                        .value("content_id", obj.getString("contentId"))
                        .value("content_type", "movie")
                        .array("content_src_id_sets")
                            .object()
                                .array("content_src_ids")
                                    .object()
                                        .object("src_id_to_mux")
                                            .array("video_src_ids", obj.getArray("videos"))
                                            .array("audio_src_ids", obj.getArray("audios"))
                                        .end()
                                    .end()
                                .end()
                            .end()
                        .end()
                        .value("timing_constraint", "unlimited")
                        .object("keep_method")
                            .object("heartbeat")
                                .value("lifetime", obj.getLong("heartbeatLifetime"))
                            .end()
                        .end()
                        .object("protocol")
                            .value("name", obj.getArray("protocols").getString(0))
                            .object("parameters")
                                .object("http_parameters")
                                    .object("parameters")
                                        .object("http_output_download_parameters")
                                            .value("use_well_known_port", "yes")
                                            .value("use_ssl", "yes")
                                            .value("transfer_preset", "")
                                        .end()
                                    .end()
                                .end()
                            .end()
                        .end()
                        .value("content_uri", "")
                        .object("session_operation_auth")
                            .object("session_operation_auth_by_signature")
                                .value("token", obj.getString("token"))
                                .value("signature", obj.getString("signature"))
                            .end()
                        .end()
                        .object("content_auth")
                            .value("auth_type", obj.getObject("authTypes").getString(obj.getArray("protocols").getString(0)))
                            .value("content_key_timeout", obj.getLong("contentKeyTimeout"))
                            .value("service_id", "nicovideo")
                            .value("service_user_id", obj.getString("serviceUserId"))
                        .end()
                        .object("client_info")
                            .value("player_id", obj.getString("playerId"))
                        .end()
                        .value("priority", obj.getLong("priority"))
                    .end()
                .end()
                .done();
    }
}
