package org.schabi.newpipe.extractor.stream;

import org.schabi.newpipe.extractor.MediaFormat;
import org.schabi.newpipe.extractor.services.youtube.ItagItem;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import java.io.Serializable;
import java.util.Locale;

public class SubtitlesStream extends Stream implements Serializable {
    private final MediaFormat format;
    private final Locale locale;
    private final boolean autoGenerated;
    private final String code;

    /**
     * Create a new subtitles stream.
     * <p>
     * The id of the stream will be set by concatenating the {@code languageCode} param with
     * {@link MediaFormat#suffix the suffix of the {@code format} param} using a dot.
     * </p>
     *
     * @param url           the URL of the stream
     * @param format        the {@link MediaFormat} used by the stream
     * @param languageCode  the language code of the stream
     * @param autoGenerated whether the subtitles are auto-generated by the streaming service
     */
    public SubtitlesStream(final String url,
                           final MediaFormat format,
                           @Nonnull final String languageCode,
                           final boolean autoGenerated) {
        this(languageCode + "." + format.suffix, url, format, languageCode, autoGenerated);

    }

    /**
     * Create a new subtitles stream.
     *
     * @param id            the ID which uniquely identifies the stream, e.g. for YouTube this
     *                      would be the itag
     * @param url           the URL of the stream
     * @param format        the {@link MediaFormat} used by the stream
     * @param languageCode  the language code of the stream
     * @param autoGenerated whether the subtitles are auto-generated by the streaming service
     */
    public SubtitlesStream(final String id,
                           final String url,
                           final MediaFormat format,
                           @Nonnull final String languageCode,
                           final boolean autoGenerated) {
        super(id, url, true, format, DeliveryMethod.PROGRESSIVE_HTTP, null);

        /*
        * Locale.forLanguageTag only for API >= 21
        * Locale.Builder only for API >= 21
        * Country codes doesn't work well without
        */
        final String[] splits = languageCode.split("-");
        switch (splits.length) {
            default:
                this.locale = new Locale(splits[0]);
                break;
            case 3:
                // Complex variants don't work!
                this.locale = new Locale(splits[0], splits[1], splits[2]);
                break;
            case 2:
                this.locale = new Locale(splits[0], splits[1]);
                break;
        }
        this.code = languageCode;
        this.format = format;
        this.autoGenerated = autoGenerated;
    }

    /**
     * Get the extension of the subtitles.
     *
     * @return the extension of the subtitles
     */
    public String getExtension() {
        return format.suffix;
    }

    /**
     * Return whether if the subtitles are auto-generated.
     * <p>
     * Some streaming services can generate subtitles for their contents, like YouTube.
     * </p>
     *
     * @return {@code true} if the subtitles are auto-generated, {@code false} otherwise
     */
    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean equalStats(final Stream cmp) {
        return super.equalStats(cmp) && cmp instanceof SubtitlesStream
                && code.equals(((SubtitlesStream) cmp).code)
                && autoGenerated == ((SubtitlesStream) cmp).autoGenerated;
    }

    /**
     * Get the display language name of the subtitles.
     *
     * @return the display language name of the subtitles
     */
    public String getDisplayLanguageName() {
        return locale.getDisplayName(locale);
    }

    /**
     * Get the language tag of the subtitles.
     *
     * @return the language tag of the subtitles
     */
    public String getLanguageTag() {
        return code;
    }

    /**
     * Get the {@link Locale locale} of the subtitles.
     *
     * @return the {@link Locale locale} of the subtitles
     */
    public Locale getLocale() {
        return locale;
    }

    @Nullable
    @Override
    /**
     * No subtitles which are currently extracted use an ItagItem.
     *
     * @return {@code null}
     */
    public ItagItem getItagItem() {
        return null;
    }
}
