blank_issues_enabled: false
contact_links:
  - name: 💬 Matrix
    url: https://matrix.to/#/#newpipe:matrix.newpipe-ev.de
    about: Chat with us via Matrix for quick Q/A
  - name: 💬 IRC
    url: https://web.libera.chat/#newpipe
    about: Chat with us via IRC for quick Q/A
