/*
 * SPDX-FileCopyrightText: 2026 NewPipe e.V. <https://newpipe-ev.de>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package org.schabi.newpipe.timeago_generator

import kotlinx.io.buffered
import java.time.temporal.ChronoUnit
import java.util.TreeMap
import kotlinx.io.files.Path
import kotlinx.io.files.SystemFileSystem
import kotlinx.io.readString
import kotlinx.io.writeString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

private val INFO_CLASS_GENERATED = """
    |/*
    | * DO NOT MODIFY THIS FILE MANUALLY
    | * This class was automatically generated by "GeneratePatternClasses.kt",
    | * modify the "unique_patterns.json" and re-generate instead.
    | */
    """.trimMargin()

fun main() {
    val jsonPath = Path("timeago-parser/raw/unique_patterns.json")
    val jsonObject = Json.parseToJsonElement(
        SystemFileSystem.source(jsonPath).buffered().readString()
    ).jsonObject

    val patternMapEntries = StringBuilder()
    TreeMap(jsonObject)
        .map { (key, value) -> key.replace('-', '_') to value.jsonObject }
        .forEach { (languageCode, unitsList) ->

            val wordSeparator = unitsList["word_separator"]?.jsonPrimitive?.content ?: ""
            val seconds = unitsList["seconds"]?.jsonArray?.toMutableList() ?: mutableListOf()
            val minutes = unitsList["minutes"]?.jsonArray?.toMutableList() ?: mutableListOf()
            val hours = unitsList["hours"]?.jsonArray?.toMutableList() ?: mutableListOf()
            val days = unitsList["days"]?.jsonArray?.toMutableList() ?: mutableListOf()
            val weeks = unitsList["weeks"]?.jsonArray?.toMutableList() ?: mutableListOf()
            val months = unitsList["months"]?.jsonArray?.toMutableList() ?: mutableListOf()
            val years = unitsList["years"]?.jsonArray?.toMutableList() ?: mutableListOf()

            val specialCasesString = buildString {
                val units = listOf(
                    ChronoUnit.SECONDS to seconds,
                    ChronoUnit.MINUTES to minutes,
                    ChronoUnit.HOURS to hours,
                    ChronoUnit.DAYS to days,
                    ChronoUnit.WEEKS to weeks,
                    ChronoUnit.MONTHS to months,
                    ChronoUnit.YEARS to years
                )

                units.forEach { (key, value) -> specialCasesConstruct(key, value) }
            }

            println("Generating \"$languageCode\" pattern class...")

            val className = languageCode.uppercase()
            val classOutputPath = Path("timeago-parser/src/main/java/org/schabi/newpipe/extractor/timeago/patterns/$className.kt")
            val classContent = """
                |$INFO_CLASS_GENERATED
    
                |package org.schabi.newpipe.extractor.timeago.patterns
    
                |import org.schabi.newpipe.extractor.timeago.PatternsHolder
                |${if (specialCasesString.isNotBlank()) "import java.time.temporal.ChronoUnit\n" else ""}
                |class $className private constructor() : PatternsHolder(
                |    WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS
                |) {
                |${if (specialCasesString.isNotBlank()) "\n    init {\n$specialCasesString    }\n" else ""}
                |    companion object {
                |        private const val WORD_SEPARATOR = "$wordSeparator"
    
                |        private val SECONDS = arrayOf(${join(seconds)})
                |        private val MINUTES = arrayOf(${join(minutes)})
                |        private val HOURS = arrayOf(${join(hours)})
                |        private val DAYS = arrayOf(${join(days)})
                |        private val WEEKS = arrayOf(${join(weeks)})
                |        private val MONTHS = arrayOf(${join(months)})
                |        private val YEARS = arrayOf(${join(years)})
    
                |        val instance = $className()
                |    }
                |}
            """.trimMargin()

            try {
                SystemFileSystem.sink(classOutputPath).buffered().use { sink ->
                    sink.writeString(classContent)
                }
            } catch (exception: Exception) {
                exception.printStackTrace()
            }

            patternMapEntries.append("        \"$languageCode\" to $className.instance,\n")
        }

    val patternMapPath = Path("timeago-parser/src/main/java/org/schabi/newpipe/extractor/timeago/PatternMap.kt")

    val patternMapClass = """
        |$INFO_CLASS_GENERATED
        |package org.schabi.newpipe.extractor.timeago

        |import org.schabi.newpipe.extractor.timeago.patterns.*

        |object PatternMap {

        |    private val patternMap = hashMapOf(
        |$patternMapEntries
        |    )

        |    @JvmStatic
        |    fun getPattern(languageCode: String): PatternsHolder? {
        |        return patternMap.get(languageCode)
        |    }
        |}
        """.trimMargin()

    try {
        SystemFileSystem.sink(patternMapPath).buffered().use { sink ->
            sink.writeString(patternMapClass)
        }
    } catch (exception: Exception) {
        exception.printStackTrace()
    }
}

private fun StringBuilder.specialCasesConstruct(unit: ChronoUnit, list: MutableList<JsonElement>) {
    list.filterIsInstance<JsonObject>().forEach { jsonObject ->
        jsonObject.entries.mapNotNull { (key, value) ->
            key.toIntOrNull()?.to(value.jsonPrimitive.content)
        }.forEach { (caseAmount, caseText) ->
            append("        putSpecialCase(ChronoUnit.${unit.name}, \"$caseText\", $caseAmount)\n")
        }
    }
}

private fun join(list: List<JsonElement>): String {
    return list.filterIsInstance<JsonPrimitive>().joinToString(", ")
}
