/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class af extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"sekonde", "sekondes"},
            MINUTES  /**/ = {"minute", "minuut"},
            HOURS    /**/ = {"ure", "uur"},
            DAYS     /**/ = {"dae", "dag"},
            WEEKS    /**/ = {"week", "weke"},
            MONTHS   /**/ = {"maand", "maande"},
            YEARS    /**/ = {"jaar"};

    private static final af INSTANCE = new af();

    public static af getInstance() {
        return INSTANCE;
    }

    private af() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}