/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class am extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"ሰኮንዶች", "ሴኮንድ"},
            MINUTES  /**/ = {"ደቂቃ", "ደቂቃዎች"},
            HOURS    /**/ = {"ሰዓት", "ሰዓቶች"},
            DAYS     /**/ = {"ቀን", "ቀኖች"},
            WEEKS    /**/ = {"ሳምንታት", "ሳምንት"},
            MONTHS   /**/ = {"ወራት", "ወር"},
            YEARS    /**/ = {"ዓመታት", "ዓመት"};

    private static final am INSTANCE = new am();

    public static am getInstance() {
        return INSTANCE;
    }

    private am() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}