/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class az extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"saniyə"},
            MINUTES  /**/ = {"dəqiqə"},
            HOURS    /**/ = {"saat"},
            DAYS     /**/ = {"gün"},
            WEEKS    /**/ = {"həftə"},
            MONTHS   /**/ = {"ay"},
            YEARS    /**/ = {"il"};

    private static final az INSTANCE = new az();

    public static az getInstance() {
        return INSTANCE;
    }

    private az() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}