/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class be extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"секунд", "секунду", "секунды"},
            MINUTES  /**/ = {"хвілін", "хвіліну", "хвіліны"},
            HOURS    /**/ = {"гадзін", "гадзіну", "гадзіны"},
            DAYS     /**/ = {"дзень", "дзён", "дня", "дні"},
            WEEKS    /**/ = {"тыдзень", "тыдня", "тыдні"},
            MONTHS   /**/ = {"месяц", "месяца", "месяцы", "месяцаў"},
            YEARS    /**/ = {"год", "года", "гады", "гадоў"};

    private static final be INSTANCE = new be();

    public static be getInstance() {
        return INSTANCE;
    }

    private be() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}