/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class bg extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"секунда", "секунди"},
            MINUTES  /**/ = {"минута", "минути"},
            HOURS    /**/ = {"час", "часа"},
            DAYS     /**/ = {"ден", "дни"},
            WEEKS    /**/ = {"седмица", "седмици"},
            MONTHS   /**/ = {"месец", "месеца"},
            YEARS    /**/ = {"година", "години"};

    private static final bg INSTANCE = new bg();

    public static bg getInstance() {
        return INSTANCE;
    }

    private bg() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}