/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class bn extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"সেকেন্ড"},
            MINUTES  /**/ = {"মিনিট"},
            HOURS    /**/ = {"ঘণ্টা"},
            DAYS     /**/ = {"দিন"},
            WEEKS    /**/ = {"সপ্তাহ"},
            MONTHS   /**/ = {"মাস"},
            YEARS    /**/ = {"বছর"};

    private static final bn INSTANCE = new bn();

    public static bn getInstance() {
        return INSTANCE;
    }

    private bn() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}