/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class ca extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"segon", "segons"},
            MINUTES  /**/ = {"minut", "minuts"},
            HOURS    /**/ = {"hora", "hores"},
            DAYS     /**/ = {"dia", "dies"},
            WEEKS    /**/ = {"setmana", "setmanes"},
            MONTHS   /**/ = {"mes", "mesos"},
            YEARS    /**/ = {"any", "anys"};

    private static final ca INSTANCE = new ca();

    public static ca getInstance() {
        return INSTANCE;
    }

    private ca() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}