/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class da extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"sekund", "sekunder"},
            MINUTES  /**/ = {"minut", "minutter"},
            HOURS    /**/ = {"time", "timer"},
            DAYS     /**/ = {"dag", "dage"},
            WEEKS    /**/ = {"uge", "uger"},
            MONTHS   /**/ = {"måned", "måneder"},
            YEARS    /**/ = {"år"};

    private static final da INSTANCE = new da();

    public static da getInstance() {
        return INSTANCE;
    }

    private da() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}