/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class de extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"Sekunde", "Sekunden"},
            MINUTES  /**/ = {"Minute", "Minuten"},
            HOURS    /**/ = {"Stunde", "Stunden"},
            DAYS     /**/ = {"Tag", "Tagen"},
            WEEKS    /**/ = {"Woche", "Wochen"},
            MONTHS   /**/ = {"Monat", "Monaten"},
            YEARS    /**/ = {"Jahr", "Jahren"};

    private static final de INSTANCE = new de();

    public static de getInstance() {
        return INSTANCE;
    }

    private de() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}