/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class en extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"second", "seconds", "sec"},
            MINUTES  /**/ = {"minute", "minutes", "min"},
            HOURS    /**/ = {"hour", "hours", "h"},
            DAYS     /**/ = {"day", "days", "d"},
            WEEKS    /**/ = {"week", "weeks", "w"},
            MONTHS   /**/ = {"month", "months", "mo"},
            YEARS    /**/ = {"year", "years", "y"};

    private static final en INSTANCE = new en();

    public static en getInstance() {
        return INSTANCE;
    }

    private en() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}