/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class fi extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"sekunti", "sekuntia"},
            MINUTES  /**/ = {"minuutti", "minuuttia"},
            HOURS    /**/ = {"tunti", "tuntia"},
            DAYS     /**/ = {"päivä", "päivää"},
            WEEKS    /**/ = {"viikko", "viikkoa"},
            MONTHS   /**/ = {"kuukausi", "kuukautta"},
            YEARS    /**/ = {"vuosi", "vuotta"};

    private static final fi INSTANCE = new fi();

    public static fi getInstance() {
        return INSTANCE;
    }

    private fi() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}