/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class gu extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"સેકંડ"},
            MINUTES  /**/ = {"મિનિટ"},
            HOURS    /**/ = {"કલાક"},
            DAYS     /**/ = {"દિવસ"},
            WEEKS    /**/ = {"અઠવાડિયા"},
            MONTHS   /**/ = {"મહિના"},
            YEARS    /**/ = {"વર્ષ"};

    private static final gu INSTANCE = new gu();

    public static gu getInstance() {
        return INSTANCE;
    }

    private gu() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}