/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class is extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"sekúndu", "sekúndum", "second", "seconds"},
            MINUTES  /**/ = {"mínútu", "mínútum", "minute", "minutes"},
            HOURS    /**/ = {"klukkustund", "klukkustundum", "hour", "hours"},
            DAYS     /**/ = {"degi", "dögum", "day", "days"},
            WEEKS    /**/ = {"viku", "vikum", "week", "weeks"},
            MONTHS   /**/ = {"mánuði", "mánuðum"},
            YEARS    /**/ = {"ári", "árum"};

    private static final is INSTANCE = new is();

    public static is getInstance() {
        return INSTANCE;
    }

    private is() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}