/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class it extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"secondi", "secondo"},
            MINUTES  /**/ = {"minuti", "minuto"},
            HOURS    /**/ = {"ora", "ore"},
            DAYS     /**/ = {"giorni", "giorno"},
            WEEKS    /**/ = {"settimana", "settimane"},
            MONTHS   /**/ = {"mese", "mesi"},
            YEARS    /**/ = {"anni", "anno"};

    private static final it INSTANCE = new it();

    public static it getInstance() {
        return INSTANCE;
    }

    private it() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}