/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

import java.time.temporal.ChronoUnit;

public class iw extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"שניות", "שנייה"},
            MINUTES  /**/ = {"דקה", "דקות"},
            HOURS    /**/ = {"שעה", "שעות"},
            DAYS     /**/ = {"יום", "ימים"},
            WEEKS    /**/ = {"שבוע", "שבועות"},
            MONTHS   /**/ = {"חודש", "חודשים"},
            YEARS    /**/ = {"שנה", "שנים"};

    private static final iw INSTANCE = new iw();

    public static iw getInstance() {
        return INSTANCE;
    }

    private iw() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
        putSpecialCase(ChronoUnit.HOURS, "שעתיים", 2);
        putSpecialCase(ChronoUnit.DAYS, "יומיים", 2);
        putSpecialCase(ChronoUnit.WEEKS, "שבועיים", 2);
        putSpecialCase(ChronoUnit.MONTHS, "חודשיים", 2);
        putSpecialCase(ChronoUnit.YEARS, "שנתיים", 2);
    }
}