/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class kk extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"секунд"},
            MINUTES  /**/ = {"минут"},
            HOURS    /**/ = {"сағат"},
            DAYS     /**/ = {"күн"},
            WEEKS    /**/ = {"апта"},
            MONTHS   /**/ = {"ай"},
            YEARS    /**/ = {"жыл"};

    private static final kk INSTANCE = new kk();

    public static kk getInstance() {
        return INSTANCE;
    }

    private kk() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}