/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class lo extends PatternsHolder {
    private static final String WORD_SEPARATOR = "";
    private static final String[]
            SECONDS  /**/ = {"ວິນາທີກ່ອນນີ້"},
            MINUTES  /**/ = {"ນາທີກ່ອນນີ້", "ນາ​ທີ​ກ່ອນ​ນີ້"},
            HOURS    /**/ = {"ຊົ່ວ​ໂມງ​ກ່ອນ​ນີ້"},
            DAYS     /**/ = {"ມື້ກ່ອນນີ້"},
            WEEKS    /**/ = {"ອາ​ທິດ​ກ່ອນ​ນີ້"},
            MONTHS   /**/ = {"ເດືອນ​ກ່ອນ​ນີ້"},
            YEARS    /**/ = {"ປີ​ກ່ອນ​ນີ້"};

    private static final lo INSTANCE = new lo();

    public static lo getInstance() {
        return INSTANCE;
    }

    private lo() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}