/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class mr extends PatternsHolder {
    private static final String WORD_SEPARATOR = "";
    private static final String[]
            SECONDS  /**/ = {"सेकंदांपूर्वी", "सेकंदापूर्वी"},
            MINUTES  /**/ = {"मिनिटांपूर्वी", "मिनिटापूर्वी"},
            HOURS    /**/ = {"तासांपूर्वी", "तासापूर्वी"},
            DAYS     /**/ = {"दिवसांपूर्वी", "दिवसापूर्वी"},
            WEEKS    /**/ = {"आठवड्यांपूर्वी", "आठवड्यापूर्वी"},
            MONTHS   /**/ = {"महिन्यांपूर्वी", "महिन्यापूर्वी"},
            YEARS    /**/ = {"वर्षांपूर्वी", "वर्षापूर्वी"};

    private static final mr INSTANCE = new mr();

    public static mr getInstance() {
        return INSTANCE;
    }

    private mr() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}