/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class my extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"စက္ကန့်"},
            MINUTES  /**/ = {"မိနစ်"},
            HOURS    /**/ = {"နာရီ"},
            DAYS     /**/ = {"ရက်"},
            WEEKS    /**/ = {"ပတ်"},
            MONTHS   /**/ = {"လ"},
            YEARS    /**/ = {"နှစ်"};

    private static final my INSTANCE = new my();

    public static my getInstance() {
        return INSTANCE;
    }

    private my() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}