/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class ro extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"secunde", "secundă"},
            MINUTES  /**/ = {"minut", "minute"},
            HOURS    /**/ = {"ore", "oră"},
            DAYS     /**/ = {"zi", "zile"},
            WEEKS    /**/ = {"săptămâni", "săptămână"},
            MONTHS   /**/ = {"luni", "lună"},
            YEARS    /**/ = {"an", "ani"};

    private static final ro INSTANCE = new ro();

    public static ro getInstance() {
        return INSTANCE;
    }

    private ro() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}