/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class ru extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"секунд", "секунду", "секунды", "только что"},
            MINUTES  /**/ = {"минут", "минуту", "минуты"},
            HOURS    /**/ = {"час", "часа", "часов"},
            DAYS     /**/ = {"день", "дней", "дня"},
            WEEKS    /**/ = {"Неделю", "недели"},
            MONTHS   /**/ = {"месяц", "месяца", "месяцев"},
            YEARS    /**/ = {"Год", "года", "лет"};

    private static final ru INSTANCE = new ru();

    public static ru getInstance() {
        return INSTANCE;
    }

    private ru() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}