/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class te extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"సెకను", "సెకన్ల"},
            MINUTES  /**/ = {"నిమిషం", "నిమిషాల"},
            HOURS    /**/ = {"గంట", "గంటల"},
            DAYS     /**/ = {"రోజు", "రోజుల"},
            WEEKS    /**/ = {"వారం", "వారాల"},
            MONTHS   /**/ = {"నెల", "నెలల"},
            YEARS    /**/ = {"సంవత్సరం", "సంవత్సరాల"};

    private static final te INSTANCE = new te();

    public static te getInstance() {
        return INSTANCE;
    }

    private te() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}