/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class th extends PatternsHolder {
    private static final String WORD_SEPARATOR = "";
    private static final String[]
            SECONDS  /**/ = {"วินาทีที่ผ่านมา"},
            MINUTES  /**/ = {"นาทีที่ผ่านมา"},
            HOURS    /**/ = {"ชั่วโมงที่ผ่านมา"},
            DAYS     /**/ = {"วันที่ผ่านมา"},
            WEEKS    /**/ = {"สัปดาห์ที่ผ่านมา"},
            MONTHS   /**/ = {"เดือนที่ผ่านมา"},
            YEARS    /**/ = {"ปีที่ผ่านมา"};

    private static final th INSTANCE = new th();

    public static th getInstance() {
        return INSTANCE;
    }

    private th() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}