/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class uk extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"секунд", "секунди", "секунду"},
            MINUTES  /**/ = {"хвилин", "хвилини", "хвилину"},
            HOURS    /**/ = {"годин", "години", "годину"},
            DAYS     /**/ = {"день", "дні", "днів"},
            WEEKS    /**/ = {"тиждень", "тижні"},
            MONTHS   /**/ = {"місяць", "місяці", "місяців"},
            YEARS    /**/ = {"роки", "років", "рік"};

    private static final uk INSTANCE = new uk();

    public static uk getInstance() {
        return INSTANCE;
    }

    private uk() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}