/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class uz extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"soniya"},
            MINUTES  /**/ = {"daqiqa"},
            HOURS    /**/ = {"soat"},
            DAYS     /**/ = {"kun"},
            WEEKS    /**/ = {"hafta"},
            MONTHS   /**/ = {"oy"},
            YEARS    /**/ = {"yil"};

    private static final uz INSTANCE = new uz();

    public static uz getInstance() {
        return INSTANCE;
    }

    private uz() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}