/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class zh_CN extends PatternsHolder {
    private static final String WORD_SEPARATOR = "";
    private static final String[]
            SECONDS  /**/ = {"秒前"},
            MINUTES  /**/ = {"分钟前"},
            HOURS    /**/ = {"小时前"},
            DAYS     /**/ = {"天前"},
            WEEKS    /**/ = {"周前"},
            MONTHS   /**/ = {"个月前"},
            YEARS    /**/ = {"年前"};

    private static final zh_CN INSTANCE = new zh_CN();

    public static zh_CN getInstance() {
        return INSTANCE;
    }

    private zh_CN() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}