/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class zu extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"amasekhondi", "isekhondi"},
            MINUTES  /**/ = {"amaminithi", "iminithi"},
            HOURS    /**/ = {"amahora", "ihora"},
            DAYS     /**/ = {"izinsuku", "usuku"},
            WEEKS    /**/ = {"amaviki", "iviki"},
            MONTHS   /**/ = {"inyanga", "izinyanga"},
            YEARS    /**/ = {"iminyaka", "unyaka"};

    private static final zu INSTANCE = new zu();

    public static zu getInstance() {
        return INSTANCE;
    }

    private zu() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}