/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago;

import org.schabi.newpipe.extractor.timeago.patterns.*;
import java.util.HashMap;
import java.util.Map;

public class PatternMap {
    private static final Map<String, PatternsHolder> patternMap = new HashMap<>();

    static {
        patternMap.put("af", af.getInstance());
        patternMap.put("am", am.getInstance());
        patternMap.put("ar", ar.getInstance());
        patternMap.put("az", az.getInstance());
        patternMap.put("be", be.getInstance());
        patternMap.put("bg", bg.getInstance());
        patternMap.put("bn", bn.getInstance());
        patternMap.put("bs", bs.getInstance());
        patternMap.put("ca", ca.getInstance());
        patternMap.put("cs", cs.getInstance());
        patternMap.put("da", da.getInstance());
        patternMap.put("de", de.getInstance());
        patternMap.put("el", el.getInstance());
        patternMap.put("en", en.getInstance());
        patternMap.put("en_GB", en_GB.getInstance());
        patternMap.put("es", es.getInstance());
        patternMap.put("es_419", es_419.getInstance());
        patternMap.put("es_US", es_US.getInstance());
        patternMap.put("et", et.getInstance());
        patternMap.put("eu", eu.getInstance());
        patternMap.put("fa", fa.getInstance());
        patternMap.put("fi", fi.getInstance());
        patternMap.put("fil", fil.getInstance());
        patternMap.put("fr", fr.getInstance());
        patternMap.put("fr_CA", fr_CA.getInstance());
        patternMap.put("gl", gl.getInstance());
        patternMap.put("gu", gu.getInstance());
        patternMap.put("hi", hi.getInstance());
        patternMap.put("hr", hr.getInstance());
        patternMap.put("hu", hu.getInstance());
        patternMap.put("hy", hy.getInstance());
        patternMap.put("id", id.getInstance());
        patternMap.put("is", is.getInstance());
        patternMap.put("it", it.getInstance());
        patternMap.put("iw", iw.getInstance());
        patternMap.put("ja", ja.getInstance());
        patternMap.put("ka", ka.getInstance());
        patternMap.put("kk", kk.getInstance());
        patternMap.put("km", km.getInstance());
        patternMap.put("kn", kn.getInstance());
        patternMap.put("ko", ko.getInstance());
        patternMap.put("ky", ky.getInstance());
        patternMap.put("lo", lo.getInstance());
        patternMap.put("lt", lt.getInstance());
        patternMap.put("lv", lv.getInstance());
        patternMap.put("mk", mk.getInstance());
        patternMap.put("ml", ml.getInstance());
        patternMap.put("mn", mn.getInstance());
        patternMap.put("mr", mr.getInstance());
        patternMap.put("ms", ms.getInstance());
        patternMap.put("my", my.getInstance());
        patternMap.put("ne", ne.getInstance());
        patternMap.put("nl", nl.getInstance());
        patternMap.put("no", no.getInstance());
        patternMap.put("pa", pa.getInstance());
        patternMap.put("pl", pl.getInstance());
        patternMap.put("pt", pt.getInstance());
        patternMap.put("pt_PT", pt_PT.getInstance());
        patternMap.put("ro", ro.getInstance());
        patternMap.put("ru", ru.getInstance());
        patternMap.put("si", si.getInstance());
        patternMap.put("sk", sk.getInstance());
        patternMap.put("sl", sl.getInstance());
        patternMap.put("sq", sq.getInstance());
        patternMap.put("sr", sr.getInstance());
        patternMap.put("sr_Latn", sr_Latn.getInstance());
        patternMap.put("sv", sv.getInstance());
        patternMap.put("sw", sw.getInstance());
        patternMap.put("ta", ta.getInstance());
        patternMap.put("te", te.getInstance());
        patternMap.put("th", th.getInstance());
        patternMap.put("tr", tr.getInstance());
        patternMap.put("uk", uk.getInstance());
        patternMap.put("ur", ur.getInstance());
        patternMap.put("uz", uz.getInstance());
        patternMap.put("vi", vi.getInstance());
        patternMap.put("zh_CN", zh_CN.getInstance());
        patternMap.put("zh_HK", zh_HK.getInstance());
        patternMap.put("zh_TW", zh_TW.getInstance());
        patternMap.put("zu", zu.getInstance());
    }

    public static PatternsHolder getPattern(final String languageCode) {
        return patternMap.get(languageCode);
    }
}