package org.schabi.newpipe.extractor.stream;

import org.junit.jupiter.api.Test;
import org.schabi.newpipe.extractor.MediaFormat;
import org.schabi.newpipe.extractor.exceptions.ParsingException;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * Builder-level checks for the service-provided display name on {@link SubtitlesStream}.
 * See TeamNewPipe/NewPipe#9218 — YouTube ships a user-facing name per caption track that
 * must survive the Builder → stream round-trip so downstream pickers can tell apart tracks
 * sharing a language code.
 */
class SubtitlesStreamBuilderTest {

    private static SubtitlesStream.Builder validBuilder() {
        return new SubtitlesStream.Builder()
                .setContent("https://example.com/sub.vtt", true)
                .setMediaFormat(MediaFormat.VTT)
                .setLanguageCode("en")
                .setAutoGenerated(false);
    }

    @Test
    void nameRoundTripsThroughGetName() throws ParsingException {
        final SubtitlesStream stream = validBuilder()
                .setName("English - CC1")
                .build();

        assertEquals("English - CC1", stream.getName());
    }

    @Test
    void explicitNullNameIsAccepted() throws ParsingException {
        final SubtitlesStream stream = validBuilder()
                .setName(null)
                .build();

        assertNull(stream.getName());
    }

    @Test
    void nameDefaultsToNullWhenUnset() throws ParsingException {
        // Existing extractors that don't call setName must keep working.
        final SubtitlesStream stream = validBuilder().build();

        assertNull(stream.getName());
    }
}
