package org.schabi.newpipe.extractor;

import org.schabi.newpipe.extractor.stream.SubtitlesFormat;

import java.io.Serializable;

public class Subtitles implements Serializable {
    private final SubtitlesFormat format;
    private final String languageCode;
    private final String URL;
    private final boolean autoGenerated;

    public Subtitles(SubtitlesFormat format, String languageCode, String URL, boolean autoGenerated) {
        this.format = format;
        this.languageCode = languageCode;
        this.URL = URL;
        this.autoGenerated = autoGenerated;
    }

    public SubtitlesFormat getFileType() { return format; }

    public String getLanguageCode() {
        return languageCode;
    }

    public String getURL() {
        return URL;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }
}
