package org.schabi.newpipe.extractor;

import org.schabi.newpipe.extractor.stream.SubtitlesFormat;

public class Subtitles {
    private SubtitlesFormat format;
    private String languageCode, URL;
    private boolean autoGenerated;

    public Subtitles(SubtitlesFormat format, String languageCode, String URL, boolean autoGenerated) {
        this.format = format;
        this.languageCode = languageCode;
        this.URL = URL;
        this.autoGenerated = autoGenerated;
    }

    public SubtitlesFormat getFileType() { return format; }

    public String getLanguageCode() {
        return languageCode;
    }

    public String getURL() {
        return URL;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }
}
