package org.schabi.newpipe.extractor;

public class Subtitles {
    private String languageName;
    private String languageCode;
    private String URL;
    private boolean autoGenerated;

    public Subtitles(String languageName, String languageCode, String URL, boolean autoGenerated) {
        this.languageName = languageName;
        this.languageCode = languageCode;
        this.URL = URL;
        this.autoGenerated = autoGenerated;
    }

    public String getLanguageName() {
        return languageName;
    }

    public String getLanguageCode() {
        return languageCode;
    }

    public String getURL() {
        return URL;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }
}
